-- MySQL Script generated by MySQL Workbench
-- Sat Jan  2 19:25:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema projet_mike
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `sexe` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `date_naissance` DATE NOT NULL,
  `createdAT` DATETIME NOT NULL,
  `activated` TINYINT NOT NULL,
  `updateAt` VARCHAR(45) NOT NULL,
  `nombre_Essai` VARCHAR(45) NOT NULL,
  `date_deverouillage` DATE NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`abonnement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`abonnement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`abonnement` (
  `nom_station` VARCHAR(45) NOT NULL,
  `idabonnement` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idabonnement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tuteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tuteur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tuteur` (
  `user_iduser` INT NOT NULL,
  `nombre_enfant` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`user_iduser`),
  CONSTRAINT `fk_tuteur_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.` enfant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.` enfant` ;

CREATE TABLE IF NOT EXISTS `mydb`.` enfant` (
  `tuteur_user_iduser` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`user_iduser`),
  CONSTRAINT `fk_ enfant_tuteur1`
    FOREIGN KEY (`tuteur_user_iduser`)
    REFERENCES `mydb`.`tuteur` (`user_iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ enfant_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carte bancaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`carte bancaire` ;

CREATE TABLE IF NOT EXISTS `mydb`.`carte bancaire` (
  `cartNumber` VARCHAR(16) NOT NULL,
  `month` VARCHAR(12) NOT NULL,
  `year` YEAR(4) NOT NULL,
  `default` TINYINT NOT NULL,
  `tuteur_user_iduser` INT NOT NULL,
  `cvc` VARCHAR(4) NOT NULL,
  CONSTRAINT `fk_carte bancaire_tuteur1`
    FOREIGN KEY (`tuteur_user_iduser`)
    REFERENCES `mydb`.`tuteur` (`user_iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`liste_abonnements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`liste_abonnements` ;

CREATE TABLE IF NOT EXISTS `mydb`.`liste_abonnements` (
  `abonnement_idabonnement` VARCHAR(45) NOT NULL,
  `tuteur_user_iduser` INT NOT NULL,
  `idabonnement` VARCHAR(45) NOT NULL,
  `periode_essai` TINYINT NOT NULL,
  `datefin_Essai` DATE NOT NULL,
  `expiration_abonnement` DATE NOT NULL,
  PRIMARY KEY (`idabonnement`),
  CONSTRAINT `fk_liste_abonnements_abonnement1`
    FOREIGN KEY (`abonnement_idabonnement`)
    REFERENCES `mydb`.`abonnement` (`idabonnement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_liste_abonnements_tuteur1`
    FOREIGN KEY (`tuteur_user_iduser`)
    REFERENCES `mydb`.`tuteur` (`user_iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chanson`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chanson` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chanson` (
  `idsong` INT NOT NULL,
  `name_song` VARCHAR(45) NOT NULL,
  `author_song` VARCHAR(45) NOT NULL,
  `time_song` TIME NOT NULL,
  `path_song` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`idsong`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chanson_abonnement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chanson_abonnement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chanson_abonnement` (
  `chanson_idsong` INT NOT NULL,
  `abonnement_idabonnement` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`chanson_idsong`, `abonnement_idabonnement`),
  CONSTRAINT `fk_chanson_has_abonnement_chanson1`
    FOREIGN KEY (`chanson_idsong`)
    REFERENCES `mydb`.`chanson` (`idsong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chanson_has_abonnement_abonnement1`
    FOREIGN KEY (`abonnement_idabonnement`)
    REFERENCES `mydb`.`abonnement` (`idabonnement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
